# Generated by Django 2.0.5 on 2018-07-21 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('job', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('ssn', models.TextField(null=True)),
                ('residence', models.TextField(null=True)),
                ('blood_type', models.TextField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], null=True)),
                ('website', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.TextField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
